---
title: Wdr
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    page_title: Updates
google_maps_api: 
plugins:
- jekyll-paginate
paginate: 10
paginate_path: "/updates/:num/"
baseurl: ''
footer:
  facebook:
    isActive: true
    url: facebook.com
  twitter:
    isActive: true
    twitter.com: 
  address:
    title: Lorem Ipsum
    text: |-
      13/4, Sum dolor sit amet,
      Consec tetur, Adipisicing,
      Incididuntut - 234556
    phone: "+91-9876543210"
    email: sber@example.com
header:
  links:
    i1:
      title: Home
      url: "/"
    i2:
      title: Student Life
      url: "/student-life.html"
    i3:
      title: Academics
      url: "/academics.html"
    i4:
      title: Residental System
      url: "/residental-system.html"
    i5:
      title: Branches
      url: "/branches.html"
    i6:
      title: Alumni
      url: "/alumni.html"
    i7:
      title: About Us
      url: "/about-us.html"
    i8:
      title: Contact Us
      url: "/contact-us.html"
